printWidth: 100
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
jsxSingleQuote: false
quoteProps: as-needed
trailingComma: es5
bracketSpacing: true
bracketSameLine: false
arrowParens: always
requirePragma: false
insertPragma: false
htmlWhitespaceSensitivity: css
endOfLine: lf
embeddedLanguageFormatting: auto
singleAttributePerLine: true
importOrder:
  - '^(react/(.*)$)|^(react$)'
  - '^(next/(.*)$)|^(next$)'
  - '<THIRD_PARTY_MODULES>'
  - ''
  - '^types$'
  - '^@local/(.*)$'
  - '^@/config/(.*)$'
  - '^@/lib/(.*)$'
  - '^@/components/(.*)$'
  - '^@/styles/(.*)$'
  - '^[./]'
importOrderParserPlugins:
  - typescript
  - decorators-legacy
plugins:
  - '@trivago/prettier-plugin-sort-imports'
